// swift-tools-version: 6.0
import PackageDescription

// The security-critical core (crypto envelope, UDP transport, passkey-PRF key
// derivation, SwiftUI views) lives in one library so `swift build` / `swift test`
// verify it on macOS. The runnable app wraps this library in an Xcode target that
// supplies `@main`, Info.plist, and the entitlements (see AppSources/ + README).
let package = Package(
    name: "CriticalInfraApple",
    platforms: [.macOS(.v15), .iOS(.v18)],
    products: [
        .library(name: "CriticalInfraKit", targets: ["CriticalInfraKit"])
    ],
    targets: [
        // Pure library: crypto, transport, device client, Secure Enclave signer.
        // The SwiftUI app (AppSources/) is NOT part of this package — it's the
        // Xcode app target generated by project.yml, which links this library.
        .target(name: "CriticalInfraKit"),
        .testTarget(name: "CriticalInfraKitTests", dependencies: ["CriticalInfraKit"])
    ],
    swiftLanguageModes: [.v5]
)
